### ISSUE TITLE
General Bugs

### ISSUE THREAD

**Issue by Plus1XP** [Plus1XP/authenticator#1]
- Make the copied message as a fade in and fade out animation within the timespace of 500ms and screen time for it fading in is 250ms and fading out for 250ms . The copied text sliding from left is a little off-ish , Change its colour to greyish.
- When one adds a microsoft 2FA secret key then there are spaces in the key and the app thinks the key is invalid so if you can add something that detects the spaces and removes those space , would removing those spaces change the otps ? 
- There is something that makes the app to stop scrolling , while scrolling rapidly and then you have to lift up the finger and then scroll again , while scrolling gently is all fine .

Issue created by @Akczht

**Comment by Plus1XP** [comment]
@Akczht I have Updated the testflight build addressing the following isues:

- Scroll Issue
- Copied notification

I Could not replicate the error adding microsoft tokens with spaces. The code is already trimming with spaces could you please provided a dummy layout of the key so i can see wherre the spaces are? Does this happen on the original app (2FA Auth)?

**Comment by Akczht** [comment]
Thanks! Dev .

**Comment by Akczht** [comment]
@Plus1XP something like this isn't able to get throught


ccyn r2xk jfxg 24uc

**Comment by Akczht** [comment]
@Plus1XP all the issues here are resolved as of v1.0.2

**Comment by Akczht** [comment]
iCloud Sync is not working right now , is it a bug ? or something intentional as of the development phase .

**Comment by Plus1XP** [comment]
Hmm seems to be working on my end, when you enable it try make a change as in add or remove a token and see if that forces a change in the cloud..

**Comment by Akczht** [comment]
@Plus1XP It's working now . Thanks!

**Comment by Plus1XP** [comment]
@Akczht did you have to make a change or did it just work by itself?

**Comment by Akczht** [comment]
@Plus1XP It seemed to work but when I double checked it now icloud backup is not working even after making changes . I don't know the issue .

**Comment by Plus1XP** [comment]
@Akczht do you have Authenticator listed under settings > Apple ID > iCloud > manage storage ?

And if so does it have how much it's using data like mine in the screenshot

![image](https://user-images.githubusercontent.com/24768549/125698747-0e15ab5f-9b93-4b8c-a9fa-b5c52171c0dc.jpeg)

**Comment by Akczht** [comment]
@Plus1XP I can see the authenticator icon in iCloud storage but when I uninstall the app and then reinstall it via test flight and then enable iCloud sync , I don't see the accounts that were supposed to be backed up , it's size is 11.7kb , in this size there are supposed to be 20 accounts .

**Comment by Akczht** [comment]
@Plus1XP in the latest update the authenticator icon from icloud has disappeared , you can try taking the approach for backing up accounts using icloud keychain .

**Comment by Plus1XP** [comment]
@Akczht Sorry for delay, i have now fixed the issue and icloud is restoring after app is removed and reinstalled.
New build (1.0.4) should be verified by Apple in a few days..

**Comment by Akczht** [comment]
@Plus1XP Honestly, I found Obsidian Authenticator , which I liked and I am very sorry but I don't want to use this one , you can drop this project if you want to , but sorry for wasting your time man .

**Comment by Plus1XP** [comment]
@Akczht no worries, ill close this issue.
